/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuditRecord: typeof import('./src/components/AuditRecord/index.vue')['default']
    AuditRecordout: typeof import('./src/components/AuditRecordout/index.vue')['default']
    CusNav: typeof import('./src/components/CusNav/index.vue')['default']
    DetPurGood: typeof import('./src/components/PurchaseList/detPurGood.vue')['default']
    DocItem: typeof import('./src/components/InDocList/docItem.vue')['default']
    FilterChoose: typeof import('./src/components/FilterChoose/index.vue')['default']
    IndexOut: typeof import('./src/components/WuLiao/indexOut.vue')['default']
    InDocList: typeof import('./src/components/InDocList/index.vue')['default']
    InventoryList: typeof import('./src/components/InventoryList/index.vue')['default']
    Item: typeof import('./src/components/InventoryList/item.vue')['default']
    Item2: typeof import('./src/components/InventoryList/item2.vue')['default']
    NavgitoutOrderList: typeof import('./src/components/navgitoutOrderList/index.vue')['default']
    NutBadge: typeof import('@nutui/nutui-taro')['Badge']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutForm: typeof import('@nutui/nutui-taro')['Form']
    NutFormItem: typeof import('@nutui/nutui-taro')['FormItem']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutNotify: typeof import('@nutui/nutui-taro')['Notify']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    Order: typeof import('./src/components/OrderList/order.vue')['default']
    OrderList: typeof import('./src/components/OrderList/index.vue')['default']
    OutOrderItem: typeof import('./src/components/navgitoutOrderList/outOrderItem.vue')['default']
    OutOrderList: typeof import('./src/components/outOrderList/index.vue')['default']
    PurchaseItem: typeof import('./src/components/PurchaseList/purchaseItem.vue')['default']
    PurchaseList: typeof import('./src/components/PurchaseList/index.vue')['default']
    WuLiao: typeof import('./src/components/WuLiao/index.vue')['default']
    WuLiaoItem: typeof import('./src/components/WuLiaoManage/wuLiaoItem.vue')['default']
    WuLiaoManage: typeof import('./src/components/WuLiaoManage/index.vue')['default']
    WuLiaoManageout: typeof import('./src/components/WuLiaoManageout/index.vue')['default']
  }
}
